export const mockClases = [
  {
    id: '1',
    nombre: 'Yoga Flow',
    descripcion: 'Clase de yoga para todos los niveles',
  intensidad: 'media' as const,
    instructor: 'Laura Martínez',
    horario: 'Lunes 10:00',
    duracion: '60 min',
    capacidad: 20,
    participantes: 12,
  tipo: 'Yoga' as const,
  grupo_musculo: 'Pierna' as const,
  sub_musculo: 'abdominal' as const,
    sede: 'Sede Central',
  image: '',
  imageUrl: '',
  },
  {
    id: '2',
    nombre: 'Spinning Cardio',
    descripcion: 'Entrenamiento cardiovascular en bicicleta',
  intensidad: 'alta' as const,
    instructor: 'Carlos Gómez',
    horario: 'Miércoles 18:00',
    duracion: '45 min',
    capacidad: 15,
    participantes: 10,
  tipo: 'Spinning' as const,
  grupo_musculo: 'Cardio' as const,
  sub_musculo: 'cuadriceps' as const,
    sede: 'Sede Norte',
  image: '',
  imageUrl: '',
  },
  {
    id: '3',
    nombre: 'HIIT Explosivo',
    descripcion: 'Entrenamiento de intervalos de alta intensidad',
  intensidad: 'muy alta' as const,
    instructor: 'Ana Torres',
    horario: 'Viernes 19:00',
    duracion: '30 min',
    capacidad: 18,
    participantes: 15,
  tipo: 'Funcional' as const,
  grupo_musculo: 'Pierna' as const,
  sub_musculo: 'gluteo' as const,
    sede: 'Sede Sur',
  image: '',
  imageUrl: '',
  },
];
