import { IClase } from '@/types';

export const preloadClases: IClase[] = [
    {
      id: "1",
      nombre: "Yoga Flow",
      descripcion: "Sesión de yoga enfocada en la respiración y flexibilidad",
      intensidad: "media",
      instructor: "Laura Gómez",
      horario: "2025-09-04 08:00",
      duracion: "60 min",
      capacidad: 20,
      participantes: 12,
      tipo: "Yoga",
      grupo_musculo: "Pierna",
      sub_musculo: "biceps",
      sede: "Sede A",
      image: "/yoga-flow.png"
    },
    {
      id: "2",
      nombre: "HIIT Explosivo",
      descripcion: "Entrenamiento de alta intensidad con intervalos",
      intensidad: "muy alta",
      instructor: "Juan Pérez",
      horario: "2025-09-04 09:30",
      duracion: "45 min",
      capacidad: 15,
      participantes: 15,
      tipo: "Crossfit",
      grupo_musculo: "Brazos",
      sub_musculo: "triceps",
      sede: "Sede B",
      image: "hiitexplosivo.png"
    },
    {
      id: "3",
      nombre: "Spinning Cardio",
      descripcion: "Entrenamiento cardiovascular en bicicleta estática",
      intensidad: "alta",
      instructor: "Carla Ruiz",
      horario: "2025-09-04 10:00",
      duracion: "50 min",
      capacidad: 25,
      participantes: 20,
      tipo: "Spinning",
      grupo_musculo: "Pierna",
      sub_musculo: "cuadriceps",
      sede: "Sede A",
      image: "spinningcardio.jpg"
    },
    {
      id: "4",
      nombre: "Pilates Core",
      descripcion: "Fortalecimiento del core y estabilidad",
      intensidad: "media",
      instructor: "María Fernández",
      horario: "2025-09-04 11:00",
      duracion: "55 min",
      capacidad: 18,
      participantes: 14,
      tipo: "Pilates",
      grupo_musculo: "Abdomen",
      sub_musculo: "abdominal",
      sede: "Sede B",
      image: "pilatescore.jpg"
    },
    {
      id: "5",
      nombre: "Zumba Fitness",
      descripcion: "Baile aeróbico con ritmos latinos",
      intensidad: "alta",
      instructor: "Diego Martínez",
      horario: "2025-09-04 12:00",
      duracion: "45 min",
      capacidad: 30,
      participantes: 25,
      tipo: "Zumba",
      grupo_musculo: "Cardio",
      sub_musculo: "gluteo",
      sede: "Sede A",
      image: "zumbafitness.png"
    },
    {
      id: "6",
      nombre: "Boxeo Técnico",
      descripcion: "Técnicas de boxeo y defensa personal",
      intensidad: "alta",
      instructor: "Roberto Silva",
      horario: "2025-09-04 13:00",
      duracion: "60 min",
      capacidad: 12,
      participantes: 10,
      tipo: "Boxeo",
      grupo_musculo: "Brazos",
      sub_musculo: "triceps",
      sede: "Sede B",
      image: "boxeotecnico.png"
    },
    {
      id: "7",
      nombre: "Funcional Avanzado",
      descripcion: "Entrenamiento funcional con movimientos complejos",
      intensidad: "muy alta",
      instructor: "Ana López",
      horario: "2025-09-04 14:00",
      duracion: "50 min",
      capacidad: 16,
      participantes: 12,
      tipo: "Funcional",
      grupo_musculo: "Espalda",
      sub_musculo: "dorsal",
      sede: "Sede A",
      image: "funcionalavanzado.png"
    },
    {
      id: "8",
      nombre: "Yoga Restaurativo",
      descripcion: "Yoga suave para relajación y recuperación",
      intensidad: "baja",
      instructor: "Sofía Herrera",
      horario: "2025-09-04 15:00",
      duracion: "75 min",
      capacidad: 15,
      participantes: 8,
      tipo: "Yoga",
      grupo_musculo: "Espalda",
      sub_musculo: "dorsal",
      sede: "Sede B",
      image: "yogarestaurativo.png"
    },
    {
      id: "9",
      nombre: "Crossfit WOD",
      descripcion: "Workout of the Day - Entrenamiento del día",
      intensidad: "muy alta",
      instructor: "Carlos Mendoza",
      horario: "2025-09-04 16:00",
      duracion: "60 min",
      capacidad: 20,
      participantes: 18,
      tipo: "Crossfit",
      grupo_musculo: "Glúteos",
      sub_musculo: "gluteo",
      sede: "Sede A",
      image: "crossfitwod.png"
    },
    {
      id: "10",
      nombre: "Pilates Mat",
      descripcion: "Pilates en colchoneta para principiantes",
      intensidad: "baja",
      instructor: "Elena Torres",
      horario: "2025-09-04 17:00",
      duracion: "45 min",
      capacidad: 20,
      participantes: 15,
      tipo: "Pilates",
      grupo_musculo: "Abdomen",
      sub_musculo: "abdominal",
      sede: "Sede B",
      image: "pilatesmat.png"
    }
  ];


