// import { IClase } from '@/types';

// export const preloadClases: IClase[] =  [
//   {
//     id: "1",
//     nombre: "Boxeo Técnico",
//     descripcion: "Clase enfocada en mejorar la técnica de golpeo y coordinación. Se trabajan principalmente brazos y tríceps, además de resistencia cardiovascular.",
//     intensidad: "alta",
//     instructor: "Mario Díaz",
//     horario: "2025-09-04 08:00",
//     duracion: "60 min",
//     capacidad: 20,
//     participantes: 15,
//     tipo: "Boxeo",
//     grupo_musculo: "Brazos",
//     sub_musculo: "triceps",
//     sede: "Sede A",
//     image: "boxeotecnico.png"
//   },
//   {
//     id: "2",
//     nombre: "Crossfit WOD",
//     descripcion: "Entrenamiento de alta intensidad con ejercicios variados. Se enfocan piernas y cuádriceps, desarrollando fuerza y potencia explosiva.",
//     intensidad: "muy alta",
//     instructor: "Juan Pérez",
//     horario: "2025-09-04 09:30",
//     duracion: "50 min",
//     capacidad: 15,
//     participantes: 15,
//     tipo: "Crossfit",
//     grupo_musculo: "Pierna",
//     sub_musculo: "cuadriceps",
//     sede: "Sede B",
//     image: "crossfitwod.png"
//   },
//   {
//     id: "3",
//     nombre: "Funcional Avanzado",
//     descripcion: "Entrenamiento completo que combina fuerza, agilidad y estabilidad. Se centra en espalda y dorsales, mejorando la postura y el control del core.",
//     intensidad: "alta",
//     instructor: "Lucía Romero",
//     horario: "2025-09-04 10:00",
//     duracion: "60 min",
//     capacidad: 18,
//     participantes: 14,
//     tipo: "Funcional",
//     grupo_musculo: "Espalda",
//     sub_musculo: "dorsal",
//     sede: "Sede A",
//     image: "funcionalavanzado.png"
//   },
//   {
//     id: "4",
//     nombre: "HIIT Explosivo",
//     descripcion: "Sesiones cortas e intensas con intervalos de esfuerzo máximo. Se trabajan glúteos y sistema cardiovascular, mejorando la resistencia y quema calórica.",
//     intensidad: "muy alta",
//     instructor: "Juan Pérez",
//     horario: "2025-09-04 11:00",
//     duracion: "45 min",
//     capacidad: 15,
//     participantes: 12,
//     tipo: "Crossfit",
//     grupo_musculo: "Cardio",
//     sub_musculo: "gluteo",
//     sede: "Sede B",
//     image: "hiitexplosivo.png"
//   },
//   {
//     id: "5",
//     nombre: "Pilates Core",
//     descripcion: "Ejercicios de pilates centrados en fortalecer el abdomen. Se trabajan abdominales y zona lumbar, mejorando la estabilidad y el equilibrio corporal.",
//     intensidad: "media",
//     instructor: "Elena Torres",
//     horario: "2025-09-04 12:00",
//     duracion: "60 min",
//     capacidad: 18,
//     participantes: 10,
//     tipo: "Pilates",
//     grupo_musculo: "Abdomen",
//     sub_musculo: "abdominal",
//     sede: "Sede B",
//     image: "pilatescore.jpg"
//   },
//   {
//     id: "6",
//     nombre: "Pilates Mat",
//     descripcion: "Clase de pilates en colchoneta para principiantes. Se fortalecen abdominales y glúteos, trabajando la postura y la movilidad articular.",
//     intensidad: "baja",
//     instructor: "Elena Torres",
//     horario: "2025-09-04 13:00",
//     duracion: "45 min",
//     capacidad: 20,
//     participantes: 15,
//     tipo: "Pilates",
//     grupo_musculo: "Abdomen",
//     sub_musculo: "abdominal",
//     sede: "Sede B",
//     image: "pilatesmat.png"
//   },
//   {
//     id: "7",
//     nombre: "Spinning Cardio",
//     descripcion: "Entrenamiento cardiovascular en bicicleta fija con música motivadora. Se trabajan piernas y glúteos, potenciando la fuerza y resistencia muscular.",
//     intensidad: "alta",
//     instructor: "Carla Ruiz",
//     horario: "2025-09-04 14:00",
//     duracion: "50 min",
//     capacidad: 25,
//     participantes: 20,
//     tipo: "Spinning",
//     grupo_musculo: "Pierna",
//     sub_musculo: "gluteo",
//     sede: "Sede A",
//     image: "spinningcardio.jpg"
//   },
//   {
//     id: "8",
//     nombre: "Yoga Flow",
//     descripcion: "Secuencia fluida de posturas de yoga que conectan respiración y movimiento. Se enfocan piernas y bíceps, mejorando la flexibilidad y la fuerza funcional.",
//     intensidad: "media",
//     instructor: "Laura Gómez",
//     horario: "2025-09-04 15:00",
//     duracion: "60 min",
//     capacidad: 20,
//     participantes: 12,
//     tipo: "Yoga",
//     grupo_musculo: "Pierna",
//     sub_musculo: "biceps",
//     sede: "Sede A",
//     image: "yoga-flow.png"
//   },
//   {
//     id: "9",
//     nombre: "Yoga Restaurativo",
//     descripcion: "Yoga suave con posturas de relajación prolongadas. Se trabajan espalda y dorsales, reduciendo el estrés y mejorando la movilidad de la columna.",
//     intensidad: "baja",
//     instructor: "Sofía Herrera",
//     horario: "2025-09-04 16:00",
//     duracion: "75 min",
//     capacidad: 15,
//     participantes: 8,
//     tipo: "Yoga",
//     grupo_musculo: "Espalda",
//     sub_musculo: "dorsal",
//     sede: "Sede B",
//     image: "yogarestaurativo.png"
//   },
//   {
//     id: "10",
//     nombre: "Zumba Fitness",
//     descripcion: "Clase de baile aeróbico con ritmos latinos. Se trabaja el sistema cardiovascular y glúteos, mejorando la coordinación, energía y resistencia física.",
//     intensidad: "alta",
//     instructor: "Diego Martínez",
//     horario: "2025-09-04 17:00",
//     duracion: "55 min",
//     capacidad: 30,
//     participantes: 25,
//     tipo: "Zumba",
//     grupo_musculo: "Cardio",
//     sub_musculo: "gluteo",
//     sede: "Sede A",
//     image: "zumbafitness.png"
//   }
// ];

